#!/bin/bash
echo "🚂 Railway Deployment for Telegram Poller"
echo ""
echo "Prerequisites:"
echo "  npm install -g @railway/cli"
echo ""
echo "Steps:"
echo ""
echo "1. Login to Railway:"
echo "   railway login"
echo ""
echo "2. Create new project:"
echo "   railway init"
echo ""
echo "3. Set environment variables:"
WEBHOOK_SECRET=$(grep WEBHOOK_SECRET webhook-autostarter/.env | cut -d= -f2)
echo "   railway variables set TELEGRAM_BOT_TOKEN='8544560105:AAGpfvhoA9I5k895YzUz97CZ0n49O6Wg9sI'"
echo "   railway variables set WEBHOOK_URL='https://codespace-autostarter.byron-zheng-yuan.workers.dev/'"
echo "   railway variables set WEBHOOK_SECRET='$WEBHOOK_SECRET'"
echo ""
echo "4. Deploy:"
echo "   railway up"
echo ""
echo "5. Check logs:"
echo "   railway logs"
echo ""
echo "That's it! The poller will run 24/7 on Railway's free tier."
